included:
  - Sources
  - Tests

excluded:
  - .build
  - docs
  - Package.resolved
  - .swiftpm

disabled_rules:
  - trailing_whitespace

line_length:
  warning: 120
  error: 140

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 600
  error: 800

identifier_name:
  allowed_symbols: ["_"]
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - mbid

opt_in_rules:
  - array_init
  - empty_count
  - explicit_self
  - first_where
