definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request
  email_develop: &email_develop
    email:
      recipients:
        - rudrankriyam@gmail.com
      notify:
        success: true
        failure: true
        
workflows:
  umerokit:
    name: UmeroKit Workflow
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_SCHEME: "UmeroKit"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
    triggering:
      <<: *events
    scripts:
      - name: SwiftLint
        script: |
          #!/bin/zsh

          brew install swiftlint || true
          swiftlint lint
      - name: Build Framework
        script: |
          #!/bin/zsh

          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 14" "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              xcodebuild clean build \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation
          done
      - name: Test Framework
        script: |
          #!/bin/zsh
          
          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 14" "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              set -o pipefail
              xcodebuild clean test \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation | xcpretty --report junit
          done
        test_report: build/reports/junit.xml
    publishing:
      <<: *email_develop
      
  umerokit-update-docs:
    name: UmeroKit Docs Update Workflow
    environment:
      groups:
        - GitHub
    scripts:
      - name: Update DocC Documentation
        script: |
          #!/bin/zsh

          swift package --allow-writing-to-directory ./docs \
          generate-documentation --target UmeroKit \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path UmeroKit \
          --output-path ./docs

          git add .
          git commit -m "[skip ci] Update DocC Documentation"
          git remote set-url origin https://rudrankriyam:$token@github.com/rryam/UmeroKit.git
          git pull --ff-only
          git push origin main
