name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  umerokit:
    name: UmeroKit Workflow
    runs-on: macos-12
    env:
      XCODE_SCHEME: "UmeroKit"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Build Framework
        run: |
          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 14" "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
          do
            xcodebuild clean build \
              -scheme "$XCODE_SCHEME" \
              -destination "$DESTINATION" \
              -skipPackagePluginValidation
          done
      - name: Test Framework
        run: |
          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 14" "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
          do
            set -o pipefail
            xcodebuild clean test \
              -scheme "$XCODE_SCHEME" \
              -destination "$DESTINATION" \
              -skipPackagePluginValidation | xcpretty --report junit
          done
        continue-on-error: true
        if: always()
      - name: Publish Test Report
        uses: actions/upload-artifact@v3
        with:
          name: junit
          path: build/reports/junit.xml

  umerokit-update-docs:
    name: UmeroKit Docs Update Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update DocC Documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target UmeroKit \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path UmeroKit \
            --output-path ./docs
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "[skip ci] Update DocC Documentation"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/rryam/UmeroKit.git
          git pull --ff-only
          git push origin main
